name:                perpetual-haskelling-initiative
version:             0.1.0.0
github:              "fpclass/perpetual-haskelling-initiative"
license:             MIT
author:              "See AUTHORS"
maintainer:          "m.gale@warwick.ac.uk"
copyright:           "Copyright (c) 2020"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Perpetual Haskelling Initiative

dependencies:
- base 

executables:
  phi:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    default-extensions:
    - OverloadedStrings
    dependencies:
    - aeson
    - filepath
    - text
